### ISSUE TITLE
add permissions check

### ISSUE THREAD

**Issue by ZeNyfh** [ZeNyfh/gigavibe-java-edition#126]
add a check to see if the bot has permissions, if not, error

for example: 

- check if bot has vc perms before joining call, error if not
- check if bot has message perms (unsure how to error this)
- check if bot has embed perms

etc

**Comment by 9382** [comment]
> check if bot has message perms (unsure how to error this)

Normally message replies come at the very end of a logic chain, so a reply failing isnt the end of the world, though it might help to just avoid sending the message entirely for cases like play which send a starting message. Plus, it's a very rare situation for someone to be able to see but not read messages in a channel where bot commands would also be used

**Comment by 9382** [comment]
I decided to do some experimentation - slash commands negates any message channel related permissions no problem - even channels the bot isn't allowed to see nor message in can be replied to if using slash commands and the current system handles it fine. Also, no such thing as "embed perms", so that point is invalid
VC permissions is a real and relevant matter and this should be checked for. I've added some basic code to show what this looks like at a simple level, though it could be nicer to centralise this behaviour if spreading stuff out like this is a concern (though its not a huge issue right now, or maybe ever)
