### ISSUE TITLE
playback of txt url fails

### ISSUE THREAD

**Issue by ZeNyfh** [ZeNyfh/gigavibe-java-edition#174]
it doesnt split at the "|"
![image](https://github.com/user-attachments/assets/aeb2d442-3e7f-42bc-aa71-7fb16feb4554)

**Comment by bibekku** [comment]
Found this issue through https://goodfirstissues.com/. I cloned the repo and tried to reproduce this bug but it looks like it's not broken? Even with the same [track](https://www.youtube.com/watch?v=RY7FpB9BZH4).

[This line](https://github.com/ZeNyfh/gigavibe-java-edition/blob/main/src/main/java/Bots/commands/CommandPlay.java#L64) seems to do the trick, although the logic would probably be clearer if the line splitting was done on ` | ` rather than on an empty space.

**Comment by ZeNyfh** [comment]
I can still reproduce this issue:
![image](https://github.com/user-attachments/assets/43073e55-edc5-4b25-9385-ea4880820da9)

The bug isn't actually at [this line](https://github.com/ZeNyfh/gigavibe-java-edition/blob/main/src/main/java/Bots/commands/CommandPlay.java#L64), it may be a little messy so that's on me, line 64 takes care of this (actually attaching the file):
![image](https://github.com/user-attachments/assets/32e4bf5e-0133-4c61-82a2-ff634fda9400)

A good place to start though would be [here](https://github.com/ZeNyfh/gigavibe-java-edition/blob/main/src/main/java/Bots/commands/CommandPlay.java#L92).

**Comment by ZeNyfh** [comment]
I've been personally looking into it, the issue at hand is that its not reading the content of the text file at all, I'll take over from here and will also change the logic to split at "|" like @bibekku suggested, thanks!
